name: Sync wgcf latest version

on:
  workflow_dispatch:
  schedule:
    - cron: '4 2 * * *'

jobs:
  build:
    name: Sync wgcf latest version
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.GH_EMAIL }}
      FILE: docker.sh
 
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Update wgcf to latest version
        run: |
          NOW=$(wget -qO- "https://raw.githubusercontent.com/${{ github.repository }}/main/${{ env.FILE }}" | grep 'latest=${latest' | cut -d \' -f2)
          LATEST=$(wget -qO- "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep -oP '(?<=tag_name": "v)[0-9.]+')
          if [ "$LATEST" != "$NOW" ]; then
            sed -i "s/$NOW/$LATEST/g" ${{ env.FILE }}
            
            git config --global user.email "${{ env.EMAIL }}"
            git config --global user.name "${{ github.actor }} "
            git add .
            git commit -m "Sync WGCF to V$LATEST by Github Actions, $(date "+%Y/%m/%d %H:%M:%S")"
            git push
          fi