name: Sync wgcf latest version

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1 * * 1'

jobs:
  build:
    name: Sync wgcf latest version
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      EMAIL: ${{ secrets.GH_EMAIL }}
      FILE: docker.sh
 
    steps:
      - uses: actions/checkout@v3
      - name: Update wgcf to latest version
        run: |
          REPO="https://raw.githubusercontent.com/${{ env.USERNAME }}/warp_unlock/main/${{ env.FILE }}"
          NOW=$(wget -qO- "$REPO" | grep 'latest=${latest' | cut -d \' -f2)
          LATEST=$(wget -qO- "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep "tag_name" | head -n 1 | cut -d : -f2 | sed 's/[ \"v,]//g')
          NOW1=$(echo $NOW | cut -d \. -f1)
          NOW2=$(echo $NOW | cut -d \. -f2)
          NOW3=$(echo $NOW | cut -d \. -f3)
          LATEST1=$(echo $LATEST | cut -d \. -f1)
          LATEST2=$(echo $LATEST | cut -d \. -f2)
          LATEST3=$(echo $LATEST | cut -d \. -f3)
          NOW_VERSION=$(( NOW1*1000000 + NOW2*1000 + NOW3 ))
          LATEST_VERSION=$(( LATEST1*1000000 + LATEST2*1000 + LATEST3 ))
          if [ $LATEST_VERSION -gt $NOW_VERSION ]; then
              wget -NP ${GITHUB_WORKSPACE} "$REPO"
              sed -i "s/$NOW/$LATEST/g" ${GITHUB_WORKSPACE}/${{ env.FILE }}
            
            git config --global user.email "${{ env.EMAIL }}"
            git config --global user.name "${{ env.USERNAME }}"
            git add .
            git commit -m "Sync WGCF to V$LATEST by Github Actions, $(date "+%Y/%m/%d %H:%M:%S")"
            git push
          fi
